#!/usr/bin/env bash




shopt -s extglob
BAT=$(acpi -b)

PERCENT=$(echo "$BAT" | sed 's/.* \([0-9]\+\)%.*$/\1/')

STATE="${BAT#*: }"
STATE="${STATE%%,*}"
STATE="${STATE@U}"

TIME="${BAT##*, }"
TIME="${TIME%:*}"
if [[ "$TIME" == "100%" ]]; then
    unset TIME
else
    TIME="$((${TIME%:*}))h $((${TIME#*:}))m"
fi


echo "BAT: $((PERCENT))% $TIME"

if [[ $((PERCENT)) -lt 25 && "$STATE" != "CHARGING" ]]; then
	notify-send -u critical -t 2000 "Battery $((PERCENT))%"'!'
fi

shopt -u extglob
