#!/usr/bin/env bash

BOOKMARK_PATH="$HOME/.bookmarks"

create_bookmark()
{
	BOOKMARK_URL=$(xclip -o selection primary)
	if [[ ! "$BOOKMARK_URL" =~ http* ]]; then
		echo "http not in URL"
		exit
	fi
	if ! grep -q "^$BOOKMARK_URL [0-9]\+$" "$BOOKMARK_PATH"; then
		echo "bookmark exists"
		echo "$BOOKMARK_URL 1" >> "$BOOKMARK_PATH"
	fi
}

open_bookmark()
{
	if [[ ! -f "$BOOKMARK_PATH" ]]; then
		exit 1
	fi
	
	BOOKMARK_RAW=$(cat "$BOOKMARK_PATH" | sort -k 2 -r)
	BOOKMARK_NAME=$( echo "$BOOKMARK_RAW" | sed "s/ [0-9]\+$//" | dmenu -l 20 -fn arial:size=10)

	if ! grep -q "$BOOKMARK_NAME" "$BOOKMARK_PATH"; then
		exit 1
	fi

	BOOKMARK_FREQ=$(grep "^$BOOKMARK_NAME [0-9]\+$" "$BOOKMARK_PATH" | cut -d ' ' -f 2)
	BOOKMARK_FREQ=${BOOKMARK_FREQ:?0}

	sed -i "s|${BOOKMARK_NAME} [0-9]\+|${BOOKMARK_NAME} $((BOOKMARK_FREQ + 1))|" "$BOOKMARK_PATH"
	firefox "$BOOKMARK_NAME"
	dwm-msg run_command view 2
}

rm_bookmark()
{

	if [[ ! -f "$BOOKMARK_PATH" ]]; then
		exit 1
	fi
	
	BOOKMARK_RAW=$(cat "$BOOKMARK_PATH" | sort -k 2 -r)
	BOOKMARK_NAME=$( echo "$BOOKMARK_RAW" | sed "s/ [0-9]\+$//" | dmenu -l 20 -fn arial:size=10)

	if ! grep -o "$BOOKMARK_NAME" "$BOOKMARK_PATH"; then
		exit 1
	fi

	BOOKMARK_FREQ=$(grep "$BOOKMARK_NAME" "$BOOKMARK_PATH" | cut -d ' ' -f 2)
	BOOKMARK_FREQ=${BOOKMARK_FREQ:?0}
	sed -i "/${BOOKMARK_NAME//\//\\\/} [0-9]\+/d" "$BOOKMARK_PATH"
}


reset_bookmarks()
{
	# Reset frequency
	sed -i "s/ [0-9]\+$/ 0/" "$BOOKMARK_PATH"
}


case "$1" in

	"-o")
			open_bookmark
			;;
	"-c")
			create_bookmark
			;;
	"-d")    
			rm_bookmark
			;;
	*)
			reset_bookmarks
			;;
esac
