#!/usr/bin/bash

brightness=$(sudo brightnessctl i | grep "Current brightness" | sed 's/.*(\([0-9]\+\)%).*/\1/')
if [ $brightness -leq 50 ]; then
    exit 0
fi


metadata=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata)
img_path="/tmp/TEMP_SPOTIFY_IMG"

remove_quotes()
{
    temp="$1"
    temp="${temp#*\"}"
    temp="${temp%\"*}"
    echo "$temp"
}


if [[ -v "$metadata" ]]; then
    exit 0
fi

artist=$(remove_quotes "$(echo "$metadata" | sed -n '/artist/{n;n;p}')")
song=$(remove_quotes "$(echo "$metadata" | sed -n '/title/{n;p}')")
icon=$(remove_quotes "$(echo "$metadata" | sed -n '/artUrl/{n;p}')")
#status=$(playerctl status spotify | tr [:lower:] [:upper:])
wget -O "$img_path" "$icon" &>/dev/null
if [[ -z "$artist" || -z "$song" ]]; then
    exit 0
fi

notify-send -t 1500 -i "$img_path" "$artist - $song" 
rm "$img_path" &>/dev/null
