#!/usr/bin/env bash

BRIGHTNESS=$(sudo brightnessctl i | grep "Current brightness" | sed 's/.*(\([0-9]\+\)%).*/\1/')
if [ "$BRIGHTNESS" -le 49 ]; then
    exit 0
fi


METADATA=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata)
IMGPATH="/tmp/TEMP_SPOTIFY_IMG"

remove_quotes()
{
    TEMP="$1"
    TEMP="${TEMP#*\"}"
    TEMP="${TEMP%\"*}"
    echo "$TEMP"
}


if [[ -v "$METADATA" ]]; then
    exit 0
fi

ARTIST=$(remove_quotes "$(echo "$METADATA" | sed -n '/artist/{n;n;p}')")
SONG=$(remove_quotes "$(echo "$METADATA" | sed -n '/title/{n;p}')")
ICON=$(remove_quotes "$(echo "$METADATA" | sed -n '/artUrl/{n;p}')")
#status=$(playerctl status spotify | tr [:lower:] [:upper:])
wget -O "$IMGPATH" "$ICON" &>/dev/null
if [[ -z "$ARTIST" || -z "$SONG" ]]; then
    exit 0
fi

notify-send -t 1500 -i "$IMGPATH" "$ARTIST - $SONG" 
rm "$IMGPATH" &>/dev/null
