#!/bin/bash

get_network_name() {
    local ip
    local ssid
    ssid=$(iwgetid -r)
    if [[ ! -v "$ssid" ]]; then
    	ip=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | sed -n 2p)
	# If docker adapter don't bother processing
		if [[ ! "$ip" == "172.17.0.1" ]]; then
		    QUALITY=$(grep wlo1 /proc/net/wireless | awk '{ print int( $3 * 100 / 70) }')
		    echo -e "${ssid} (${ip}) ${QUALITY}%"
		    echo $ip
		    echo "#00FF00"
		fi
    fi
}

get_network_name
