#!/usr/bin/env bash
LOG_PATH="/home/nick/dwm.log"

launch()
{
	PID=$(ps -aux | grep "$1" | wc -l)
	if [[ "$((PID))" -lt 2 ]]; then
		echo "$(date) launching $1"
		exec "$@" & >> "$LOG_PATH"
	else
		echo "$(date) $1 running already" >> "$LOG_PATH"
	fi 

}


rm "$LOG_PATH"
#launch alacritty -o font.size=8
launch discord
launch spotify
#launch parcellite

if [[ ! -v $(pgrep dwmblocks) ]]; then
	pkill dwmblocks
	exec dwmblocks
fi
