#!/usr/bin/env bash



VOL_RAW=$( amixer -D default | sed -n "s/.* \[\([0-9]\+\)%\] \[\([a-z]*\)\].*/\1 \2/p" | head -n 1)

if [[ "$VOL_RAW" =~ ['0-9']+' off' ]]; then
	echo "VOL: MUTE"
else
	PERCENT="${VOL_RAW% *}"
	echo "VOL: $((${PERCENT% *}))%"
fi
